# Generated by Django 4.2.5 on 2023-09-11 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatuser',
            name='username',
        ),
    ]
