# Generated by Django 4.2.5 on 2023-09-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatuser', '0003_chatuser_created_at_chatuser_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
